import { describe, it, expect } from 'vitest';
import { bandOf, secretPlan, ringFor } from '../src/world/secrets.js';
import { createGame, descend } from '../src/core/gameState.js';
import { sweepForDropTile } from '../src/entities/spawn.js';
import { SECRET_BAND_FLOORS, RING_TYPES, TILE } from '../src/core/constants.js';

describe('the per-band secret plan (pure, seed-derived)', () => {
  const seeds = [1, 2, 3, 42, 1337, 987654321, 'custom-text-seed'];

  it('maps floors to bands', () => {
    expect(bandOf(1)).toBe(0);
    expect(bandOf(5)).toBe(0);
    expect(bandOf(6)).toBe(1);
    expect(bandOf(10)).toBe(1);
    expect(bandOf(11)).toBe(2);
  });

  it('is deterministic and never draws from any shared RNG', () => {
    for (const seed of seeds) {
      for (let band = 0; band < 10; band++) {
        expect(secretPlan(seed, band)).toEqual(secretPlan(seed, band));
      }
    }
  });

  it('puts the key strictly before the chest, both inside the band', () => {
    for (const seed of seeds) {
      for (let band = 0; band < 10; band++) {
        const { keyFloor, chestFloor } = secretPlan(seed, band);
        const first = band * SECRET_BAND_FLOORS + 1;
        const last = first + SECRET_BAND_FLOORS - 1;
        expect(keyFloor).toBeGreaterThanOrEqual(first);
        expect(chestFloor).toBeLessThanOrEqual(last);
        expect(keyFloor).toBeLessThan(chestFloor);
      }
    }
  });

  it('grants all four rings across the first four bands, then wraps', () => {
    for (const seed of seeds) {
      const cycle = [0, 1, 2, 3].map((b) => ringFor(seed, b));
      expect(new Set(cycle).size).toBe(RING_TYPES.length);
      expect(ringFor(seed, 4)).toBe(cycle[0]);
      expect(ringFor(seed, 7)).toBe(cycle[3]);
    }
  });

  it('spreads all four rings evenly over band 0 across seeds', () => {
    // Playtesting produced a run of Survival rings out of the first chest and
    // the natural suspicion that the pick was rigged. It is not — but nothing
    // asserted that, and the shuffle, the FNV seed fold and the band index are
    // all places a change could quietly collapse band 0 onto one ring. Seeds
    // are generated by a fixed LCG, so this is deterministic, not sampled; the
    // bounds are loose enough that only a real skew trips them.
    const counts = new Map(RING_TYPES.map((t) => [t, 0]));
    const N = 20000;
    let seed = 123456789 >>> 0;
    for (let i = 0; i < N; i++) {
      seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
      const ring = ringFor(seed, 0);
      counts.set(ring, counts.get(ring) + 1);
    }
    for (const type of RING_TYPES) {
      const share = counts.get(type) / N;
      expect(share, `band 0 share of "${type}"`).toBeGreaterThan(0.2);
      expect(share, `band 0 share of "${type}"`).toBeLessThan(0.3);
    }
  });

  it('different seeds produce different plans (spot check)', () => {
    const plans = seeds.map((s) => JSON.stringify([0, 1, 2].map((b) => secretPlan(s, b))));
    expect(new Set(plans).size).toBeGreaterThan(1);
  });
});

describe('secret spawning across a real run', () => {
  // Walk a real game down 10 floors (two bands) and check that exactly the
  // planned floors carry the hidden key and the locked chest.
  it.each([11, 22, 33])('seed %i: one key and one locked chest per band, on plan', (seed) => {
    const state = createGame(seed);
    const found = new Map(); // floor → { keys, chests, ring }
    for (let floor = 1; floor <= 2 * SECRET_BAND_FLOORS; floor++) {
      if (floor > 1) descend(state);
      expect(state.floor).toBe(floor);
      const keys = state.items.filter((it) => it.type === 'key');
      const chests = state.items.filter((it) => it.type === 'lockedChest');
      found.set(floor, { keys, chests });
    }
    for (const band of [0, 1]) {
      const plan = secretPlan(state.seed, band);
      for (
        let floor = band * SECRET_BAND_FLOORS + 1;
        floor <= (band + 1) * SECRET_BAND_FLOORS;
        floor++
      ) {
        const { keys, chests } = found.get(floor);
        expect(keys).toHaveLength(floor === plan.keyFloor ? 1 : 0);
        expect(chests).toHaveLength(floor === plan.chestFloor ? 1 : 0);
        if (floor === plan.keyFloor) expect(keys[0].hidden).toBe(true);
        if (floor === plan.chestFloor) expect(chests[0].ring).toBe(plan.ring);
      }
    }
  });

  it('the same seed spawns secrets on the same tiles', () => {
    const a = createGame(77);
    const b = createGame(77);
    for (let floor = 1; floor <= SECRET_BAND_FLOORS; floor++) {
      if (floor > 1) {
        descend(a);
        descend(b);
      }
      const secretsOf = (s) =>
        s.items
          .filter((it) => it.type === 'key' || it.type === 'lockedChest')
          .map(({ type, x, y, ring }) => ({ type, x, y, ring }));
      expect(secretsOf(a)).toEqual(secretsOf(b));
    }
  });
});

describe('deterministic placement fallback for a band secret', () => {
  // A band's key and locked chest used to be skipped outright when the random
  // room scans all missed — silently, and for the chest that meant losing the
  // band's ring, since secretPlan never re-rolls the chest floor. The RNG-free
  // sweep below is the last resort. It draws nothing, which is what keeps every
  // existing seed byte-identical (`npm run balance` is the real proof).
  //
  // Tested directly rather than through a run: the random path and the sweep
  // search the SAME tiles by the SAME predicate and differ only in
  // thoroughness, so there is no floor you can build where random provably
  // fails and the sweep provably succeeds without reaching in and rigging the
  // generator. Pinning the pure function is the honest version of that test.
  function synthState(rows) {
    const width = rows[0].length;
    const tiles = new Uint8Array(width * rows.length);
    rows.forEach((row, y) =>
      [...row].forEach((ch, x) => {
        tiles[y * width + x] = ch === '.' ? TILE.FLOOR : TILE.WALL;
      }),
    );
    return {
      map: { width, height: rows.length, tiles },
      entities: { byId: new Map() },
      items: [],
    };
  }

  // Two 2x2 rooms side by side, separated by a wall column.
  const ROWS = ['######', '#..#..', '#..#..', '######'];
  const ROOM_A = { x: 1, y: 1, w: 2, h: 2 };
  const ROOM_B = { x: 4, y: 1, w: 2, h: 2 };

  it('returns the first legal tile in room-then-tile order', () => {
    const state = synthState(ROWS);
    expect(sweepForDropTile(state, [ROOM_A, ROOM_B])).toEqual({ x: 1, y: 1 });
  });

  it('skips tiles holding an entity or an item', () => {
    const state = synthState(ROWS);
    state.entities.byId.set(1, { id: 1, x: 1, y: 1 });
    state.items.push({ type: 'potion', x: 2, y: 1 });
    expect(sweepForDropTile(state, [ROOM_A])).toEqual({ x: 1, y: 2 });
  });

  it('moves on to the next room when the first is full', () => {
    const state = synthState(ROWS);
    let id = 1;
    for (const y of [1, 2]) for (const x of [1, 2]) state.entities.byId.set(id, { id: id++, x, y });
    expect(sweepForDropTile(state, [ROOM_A, ROOM_B])).toEqual({ x: 4, y: 1 });
  });

  it('reports failure instead of inventing a tile when nothing is legal', () => {
    const state = synthState(['######', '######', '######', '######']);
    expect(sweepForDropTile(state, [ROOM_A, ROOM_B])).toBe(null);
  });

  // canDropAt is the shared predicate, so the sweep inherits the rules that
  // keep drops off doorways and staircases — the 0.9.10 and 0.9.7 fixes.
  it('never lands on a walkable-but-not-FLOOR tile: a door or a staircase', () => {
    const state = synthState(ROWS);
    // Room A becomes all doors and stairs — walkable, but a doorway hides a
    // dropped item under the wall art and a staircase swallows the pickup.
    const put = (x, y, tile) => {
      state.map.tiles[y * state.map.width + x] = tile;
    };
    put(1, 1, TILE.DOOR);
    put(2, 1, TILE.DOOR);
    put(1, 2, TILE.STAIRS_DOWN);
    put(2, 2, TILE.STAIRS_UP);
    expect(sweepForDropTile(state, [ROOM_A])).toBe(null);
    // …but the untouched neighbouring room is still fair game.
    expect(sweepForDropTile(state, [ROOM_A, ROOM_B])).toEqual({ x: 4, y: 1 });
  });
});
